//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  page: Page;
  pageConnection: PageConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};

export type DocumentFilter = {
  page?: InputMaybe<PageFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = PageAcademics | PageAbout | PageAdmission | PageContact | Folder;

export type PageAcademicsHero = {
  __typename?: 'PageAcademicsHero';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type PageAcademicsCurriculum = {
  __typename?: 'PageAcademicsCurriculum';
  class?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  focus?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type PageAcademicsDepartments = {
  __typename?: 'PageAcademicsDepartments';
  id?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  faculty?: Maybe<Scalars['String']['output']>;
  staffLead?: Maybe<Scalars['String']['output']>;
  subjects?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  highlights?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type PageAcademicsAcademicCalendar = {
  __typename?: 'PageAcademicsAcademicCalendar';
  month?: Maybe<Scalars['String']['output']>;
  event?: Maybe<Scalars['String']['output']>;
  type?: Maybe<Scalars['String']['output']>;
};

export type PageAcademicsScholars = {
  __typename?: 'PageAcademicsScholars';
  rank?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  percentage?: Maybe<Scalars['String']['output']>;
  class?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
};

export type PageAcademicsCta = {
  __typename?: 'PageAcademicsCta';
  title?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  buttonText?: Maybe<Scalars['String']['output']>;
  buttonLink?: Maybe<Scalars['String']['output']>;
};

export type PageAcademics = Node & Document & {
  __typename?: 'PageAcademics';
  hero?: Maybe<PageAcademicsHero>;
  curriculum?: Maybe<Array<Maybe<PageAcademicsCurriculum>>>;
  departments?: Maybe<Array<Maybe<PageAcademicsDepartments>>>;
  academicCalendar?: Maybe<Array<Maybe<PageAcademicsAcademicCalendar>>>;
  scholars?: Maybe<Array<Maybe<PageAcademicsScholars>>>;
  cta?: Maybe<PageAcademicsCta>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PageAboutHero = {
  __typename?: 'PageAboutHero';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  establishedDate?: Maybe<Scalars['String']['output']>;
};

export type PageAboutFacultySection = {
  __typename?: 'PageAboutFacultySection';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type PageAboutPgtFaculty = {
  __typename?: 'PageAboutPgtFaculty';
  name?: Maybe<Scalars['String']['output']>;
  designation?: Maybe<Scalars['String']['output']>;
  department?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  quote?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type PageAboutTgtFaculty = {
  __typename?: 'PageAboutTgtFaculty';
  name?: Maybe<Scalars['String']['output']>;
  designation?: Maybe<Scalars['String']['output']>;
  department?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  quote?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type PageAboutPrtFaculty = {
  __typename?: 'PageAboutPrtFaculty';
  name?: Maybe<Scalars['String']['output']>;
  designation?: Maybe<Scalars['String']['output']>;
  department?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  quote?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type PageAboutValues = {
  __typename?: 'PageAboutValues';
  title?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  iconName?: Maybe<Scalars['String']['output']>;
  color?: Maybe<Scalars['String']['output']>;
};

export type PageAbout = Node & Document & {
  __typename?: 'PageAbout';
  hero?: Maybe<PageAboutHero>;
  edMessage?: Maybe<Scalars['String']['output']>;
  facultySection?: Maybe<PageAboutFacultySection>;
  pgtFaculty?: Maybe<Array<Maybe<PageAboutPgtFaculty>>>;
  tgtFaculty?: Maybe<Array<Maybe<PageAboutTgtFaculty>>>;
  prtFaculty?: Maybe<Array<Maybe<PageAboutPrtFaculty>>>;
  values?: Maybe<Array<Maybe<PageAboutValues>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PageAdmissionHero = {
  __typename?: 'PageAdmissionHero';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type PageAdmissionProcess = {
  __typename?: 'PageAdmissionProcess';
  number?: Maybe<Scalars['Float']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
};

export type PageAdmissionFeeStructure = {
  __typename?: 'PageAdmissionFeeStructure';
  class?: Maybe<Scalars['String']['output']>;
  tuition?: Maybe<Scalars['String']['output']>;
  annual?: Maybe<Scalars['String']['output']>;
  total?: Maybe<Scalars['String']['output']>;
};

export type PageAdmissionFaqs = {
  __typename?: 'PageAdmissionFaqs';
  question?: Maybe<Scalars['String']['output']>;
  answer?: Maybe<Scalars['String']['output']>;
};

export type PageAdmissionContactInfo = {
  __typename?: 'PageAdmissionContactInfo';
  phone?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  hours?: Maybe<Scalars['String']['output']>;
};

export type PageAdmission = Node & Document & {
  __typename?: 'PageAdmission';
  hero?: Maybe<PageAdmissionHero>;
  process?: Maybe<Array<Maybe<PageAdmissionProcess>>>;
  feeStructure?: Maybe<Array<Maybe<PageAdmissionFeeStructure>>>;
  faqs?: Maybe<Array<Maybe<PageAdmissionFaqs>>>;
  contactInfo?: Maybe<PageAdmissionContactInfo>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PageContactHero = {
  __typename?: 'PageContactHero';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type PageContactContactDetails = {
  __typename?: 'PageContactContactDetails';
  address?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  hours?: Maybe<Scalars['String']['output']>;
};

export type PageContact = Node & Document & {
  __typename?: 'PageContact';
  hero?: Maybe<PageContactHero>;
  contactDetails?: Maybe<PageContactContactDetails>;
  mapUrl?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Page = PageAcademics | PageAbout | PageAdmission | PageContact;

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PageAcademicsHeroFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type PageAcademicsCurriculumFilter = {
  class?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  focus?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  features?: InputMaybe<StringFilter>;
};

export type PageAcademicsDepartmentsFilter = {
  id?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  faculty?: InputMaybe<StringFilter>;
  staffLead?: InputMaybe<StringFilter>;
  subjects?: InputMaybe<StringFilter>;
  highlights?: InputMaybe<StringFilter>;
};

export type PageAcademicsAcademicCalendarFilter = {
  month?: InputMaybe<StringFilter>;
  event?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
};

export type PageAcademicsScholarsFilter = {
  rank?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  percentage?: InputMaybe<StringFilter>;
  class?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type PageAcademicsCtaFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  buttonText?: InputMaybe<StringFilter>;
  buttonLink?: InputMaybe<StringFilter>;
};

export type PageAcademicsFilter = {
  hero?: InputMaybe<PageAcademicsHeroFilter>;
  curriculum?: InputMaybe<PageAcademicsCurriculumFilter>;
  departments?: InputMaybe<PageAcademicsDepartmentsFilter>;
  academicCalendar?: InputMaybe<PageAcademicsAcademicCalendarFilter>;
  scholars?: InputMaybe<PageAcademicsScholarsFilter>;
  cta?: InputMaybe<PageAcademicsCtaFilter>;
};

export type PageAboutHeroFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  establishedDate?: InputMaybe<StringFilter>;
};

export type PageAboutFacultySectionFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PageAboutPgtFacultyFilter = {
  name?: InputMaybe<StringFilter>;
  designation?: InputMaybe<StringFilter>;
  department?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  quote?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type PageAboutTgtFacultyFilter = {
  name?: InputMaybe<StringFilter>;
  designation?: InputMaybe<StringFilter>;
  department?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  quote?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type PageAboutPrtFacultyFilter = {
  name?: InputMaybe<StringFilter>;
  designation?: InputMaybe<StringFilter>;
  department?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  quote?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type PageAboutValuesFilter = {
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  iconName?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
};

export type PageAboutFilter = {
  hero?: InputMaybe<PageAboutHeroFilter>;
  edMessage?: InputMaybe<StringFilter>;
  facultySection?: InputMaybe<PageAboutFacultySectionFilter>;
  pgtFaculty?: InputMaybe<PageAboutPgtFacultyFilter>;
  tgtFaculty?: InputMaybe<PageAboutTgtFacultyFilter>;
  prtFaculty?: InputMaybe<PageAboutPrtFacultyFilter>;
  values?: InputMaybe<PageAboutValuesFilter>;
};

export type PageAdmissionHeroFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type PageAdmissionProcessFilter = {
  number?: InputMaybe<NumberFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type PageAdmissionFeeStructureFilter = {
  class?: InputMaybe<StringFilter>;
  tuition?: InputMaybe<StringFilter>;
  annual?: InputMaybe<StringFilter>;
  total?: InputMaybe<StringFilter>;
};

export type PageAdmissionFaqsFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type PageAdmissionContactInfoFilter = {
  phone?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  hours?: InputMaybe<StringFilter>;
};

export type PageAdmissionFilter = {
  hero?: InputMaybe<PageAdmissionHeroFilter>;
  process?: InputMaybe<PageAdmissionProcessFilter>;
  feeStructure?: InputMaybe<PageAdmissionFeeStructureFilter>;
  faqs?: InputMaybe<PageAdmissionFaqsFilter>;
  contactInfo?: InputMaybe<PageAdmissionContactInfoFilter>;
};

export type PageContactHeroFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type PageContactContactDetailsFilter = {
  address?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  hours?: InputMaybe<StringFilter>;
};

export type PageContactFilter = {
  hero?: InputMaybe<PageContactHeroFilter>;
  contactDetails?: InputMaybe<PageContactContactDetailsFilter>;
  mapUrl?: InputMaybe<StringFilter>;
};

export type PageFilter = {
  academics?: InputMaybe<PageAcademicsFilter>;
  about?: InputMaybe<PageAboutFilter>;
  admission?: InputMaybe<PageAdmissionFilter>;
  contact?: InputMaybe<PageContactFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePage: Page;
  createPage: Page;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};

export type DocumentUpdateMutation = {
  page?: InputMaybe<PageMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  page?: InputMaybe<PageMutation>;
};

export type PageAcademicsHeroMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type PageAcademicsCurriculumMutation = {
  class?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  focus?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PageAcademicsDepartmentsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  faculty?: InputMaybe<Scalars['String']['input']>;
  staffLead?: InputMaybe<Scalars['String']['input']>;
  subjects?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  highlights?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PageAcademicsAcademicCalendarMutation = {
  month?: InputMaybe<Scalars['String']['input']>;
  event?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
};

export type PageAcademicsScholarsMutation = {
  rank?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  percentage?: InputMaybe<Scalars['String']['input']>;
  class?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type PageAcademicsCtaMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  buttonText?: InputMaybe<Scalars['String']['input']>;
  buttonLink?: InputMaybe<Scalars['String']['input']>;
};

export type PageAcademicsMutation = {
  hero?: InputMaybe<PageAcademicsHeroMutation>;
  curriculum?: InputMaybe<Array<InputMaybe<PageAcademicsCurriculumMutation>>>;
  departments?: InputMaybe<Array<InputMaybe<PageAcademicsDepartmentsMutation>>>;
  academicCalendar?: InputMaybe<Array<InputMaybe<PageAcademicsAcademicCalendarMutation>>>;
  scholars?: InputMaybe<Array<InputMaybe<PageAcademicsScholarsMutation>>>;
  cta?: InputMaybe<PageAcademicsCtaMutation>;
};

export type PageAboutHeroMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  establishedDate?: InputMaybe<Scalars['String']['input']>;
};

export type PageAboutFacultySectionMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type PageAboutPgtFacultyMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  designation?: InputMaybe<Scalars['String']['input']>;
  department?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  quote?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type PageAboutTgtFacultyMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  designation?: InputMaybe<Scalars['String']['input']>;
  department?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  quote?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type PageAboutPrtFacultyMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  designation?: InputMaybe<Scalars['String']['input']>;
  department?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  quote?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type PageAboutValuesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  iconName?: InputMaybe<Scalars['String']['input']>;
  color?: InputMaybe<Scalars['String']['input']>;
};

export type PageAboutMutation = {
  hero?: InputMaybe<PageAboutHeroMutation>;
  edMessage?: InputMaybe<Scalars['String']['input']>;
  facultySection?: InputMaybe<PageAboutFacultySectionMutation>;
  pgtFaculty?: InputMaybe<Array<InputMaybe<PageAboutPgtFacultyMutation>>>;
  tgtFaculty?: InputMaybe<Array<InputMaybe<PageAboutTgtFacultyMutation>>>;
  prtFaculty?: InputMaybe<Array<InputMaybe<PageAboutPrtFacultyMutation>>>;
  values?: InputMaybe<Array<InputMaybe<PageAboutValuesMutation>>>;
};

export type PageAdmissionHeroMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type PageAdmissionProcessMutation = {
  number?: InputMaybe<Scalars['Float']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type PageAdmissionFeeStructureMutation = {
  class?: InputMaybe<Scalars['String']['input']>;
  tuition?: InputMaybe<Scalars['String']['input']>;
  annual?: InputMaybe<Scalars['String']['input']>;
  total?: InputMaybe<Scalars['String']['input']>;
};

export type PageAdmissionFaqsMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
};

export type PageAdmissionContactInfoMutation = {
  phone?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  hours?: InputMaybe<Scalars['String']['input']>;
};

export type PageAdmissionMutation = {
  hero?: InputMaybe<PageAdmissionHeroMutation>;
  process?: InputMaybe<Array<InputMaybe<PageAdmissionProcessMutation>>>;
  feeStructure?: InputMaybe<Array<InputMaybe<PageAdmissionFeeStructureMutation>>>;
  faqs?: InputMaybe<Array<InputMaybe<PageAdmissionFaqsMutation>>>;
  contactInfo?: InputMaybe<PageAdmissionContactInfoMutation>;
};

export type PageContactHeroMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type PageContactContactDetailsMutation = {
  address?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  hours?: InputMaybe<Scalars['String']['input']>;
};

export type PageContactMutation = {
  hero?: InputMaybe<PageContactHeroMutation>;
  contactDetails?: InputMaybe<PageContactContactDetailsMutation>;
  mapUrl?: InputMaybe<Scalars['String']['input']>;
};

export type PageMutation = {
  academics?: InputMaybe<PageAcademicsMutation>;
  about?: InputMaybe<PageAboutMutation>;
  admission?: InputMaybe<PageAdmissionMutation>;
  contact?: InputMaybe<PageContactMutation>;
};


export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {

    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  